# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('temperatura', models.FloatField(default=0.0)),
                ('humedad', models.FloatField(default=0.0)),
            ],
        ),
    ]
