# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_temperatura_humedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
