# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180205_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperatura',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='temperatura',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
